[package]
name = "tetris-core"
version = "0.1.0"
authors = ["cpsdqs <cpsdqs@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
