[package]
name = "tetris-wasm"
version = "0.1.0"
authors = ["cpsdqs <cpsdqs@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
tetris-core = { path = "../tetris-core" }
wasm-bindgen = "0.2"
